service: fastapiLambda

provider:
  name: aws
  region: ap-northeast-1
  ecr:
    images:
      fastapi_lambda:
        path: ./
        file: ${param:dockerfile}

functions:
  fastapi:
    image:
      name: fastapi_lambda
      command: app.handler
    events:
      - http:
          path: /{proxy+}
          method: get
          integration: lambda-proxy
          cors: true

params:
  dev:
    dockerfile: ./aws/Dockerfile.dev
  prod:
    dockerfile: ./aws/Dockerfile.prod
