service: fastapiLambda

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  ecr:
    images:
      fastapi_lambda:
        path: ./
        file: ${self:custom.environment.${self:provider.stage}}

functions:
  fastapi:
    image:
      name: fastapi_lambda
      command: app.handler
    events:
      - http:
          path: /{proxy+}
          method: get
          integration: lambda-proxy
          cors: true

custom:
  defaultStage: dev
  environment:
    dev: ./aws/Dockerfile.dev
    prod: ./aws/Dockerfile.prod
